### ISSUE TITLE
path to capstone.lib is not relative, and uses explicit path on authors computer

### ISSUE THREAD

**Issue by micksmix** [nccgroup/psr#1]
Easy to fix of course, but got this error on attempting to build: `1>LINK : fatal error LNK1104: cannot open file 'C:\Users\nick\Desktop\capstone-next\msvc\Debug\capstone.lib'`

I also suggest adding to README that this requires using Capstone from the `next` branch, and not master.

**Comment by ncollisson** [comment]
Thanks for pointing this out. I've added a note to the README about using the next branch of Capstone, and removed the explicit paths from the solution. I think users are going to have to build and include their own copies of Capstone either way. Let me know if there's a more elegant solution you had in mind.

**Comment by micksmix** [comment]
Understood. And thank you for developing this software and releasing it!
